---
- name: Added module nf_conntrack
  set_fact:
    k8s_ipvs_modules: "{{ k8s_ipvs_modules + ['nf_conntrack'] }}"

- name: Ensure ipvsadm installed.
  become: true
  ansible.builtin.apt:
    name:
      - ipvsadm
    state: present
