---
- name: include OS family/distribution specific playbook
  ansible.builtin.include_tasks: "{{ playbook_item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  loop_control:
    loop_var: playbook_item

- name: Add modules to the file
  become: true
  ansible.builtin.copy:
    content: |
      {%- for module in k8s_ipvs_modules %}
      {{ module }}
      {% endfor %}
    dest: /etc/modules-load.d/ipvs.conf
    group: "root"
    owner: "root"
    mode: "0644"
  loop: "{{ k8s_ipvs_modules }}"

- name: Load modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ k8s_ipvs_modules }}"
