---
- hosts: k8s_worker

  tasks:
    - include_role:
        name: containerd
    - include_role:
        name: kube
    - include_role:
        name: systemd-resolved
    - include_role:
        name: join_worker
