---
- hosts: k8s_worker
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: containerd
    - ansible.builtin.include_role:
        name: kube
    - ansible.builtin.include_role:
        name: k8s_ipvs
    - ansible.builtin.include_role:
        name: join_worker
