---
# tasks file for k8s-ipvs
- name: include OS family/distribution specific playbook
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'


- name: Add modules to the file
  become: true
  ansible.builtin.copy:
    content: |
      ip_vs
      ip_vs_lc
      ip_vs_rr
      ip_vs_sh
      ip_vs_wrr
      nf_conntrack_ipv4
    dest: /etc/modules-load.d/ipvs.conf
    group: "root"
    owner: "root"
    mode: "0644"

- name: Load modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - ip_vs
    - ip_vs_lc
    - ip_vs_rr
    - ip_vs_sh
    - ip_vs_wrr
    - nf_conntrack_ipv4
