---
- name: include OS family/distribution specific playbook
  ansible.builtin.include_tasks: "{{ playbook_item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  loop_control:
    loop_var: playbook_item
